-- liquibase formatted sql

-- changeset Юрий Калынбаев:1
CREATE TABLE IF NOT EXISTS cats
(
    id          BIGINT generated by default as identity primary key,
    nick_name   TEXT   NOT NULL,
    breed       TEXT   NOT NULL,
    age         INT NOT NULL,
    description TEXT   NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS cats_idx ON cats(id);

-- changeset Юрий Калынбаев:2
CREATE TABLE IF NOT EXISTS cat_photo
(
    id         BIGINT generated by default as identity primary key,
    file_path  TEXT   NOT NULL,
    file_size  BIGINT NOT NULL,
    media_type TEXT   NOT NULL,
    photo_cat  oid    NOT NULL,
    cat_id     BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS cat_photo_idx ON cat_photo(id);

-- changeset Юрий Калынбаев:3
CREATE TABLE IF NOT EXISTS dogs
(
    id          BIGINT generated by default as identity primary key,
    nick_name   TEXT   NOT NULL,
    breed       TEXT   NOT NULL,
    age         INT NOT NULL,
    description TEXT   NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS dogs_idx ON dogs(id);

-- changeset Юрий Калынбаев:4
CREATE TABLE IF NOT EXISTS dog_photo
(
    id         BIGINT generated by default as identity primary key,
    file_path  TEXT   NOT NULL,
    file_size  BIGINT NOT NULL,
    media_type TEXT   NOT NULL,
    photo_dog  oid    NOT NULL,
    dog_id     BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS dog_photo_idx ON dog_photo(id);