--liquibase formatted sql

-- -- handset Андрей Попов:1
create table report
(
    id          bigint generated by default as identity primary key,
    report_time timestamp,
    info        varchar(255),
    diet        text,
    health      text,
    behavior    text,
    photo       bytea,
    chart_id    bigint,
    telegram_id bigint
);

-- -- changeset Андрей Попов:2
create table handler
(
    id        bigint generated by default as identity primary key,
    surname   varchar(255),
    call_time varchar(255),
    company   text,
    contact   varchar(255),
    add_info  varchar(255)
);