-- liquibase formatted sql

-- changeset Юрий Калынбаев:1
CREATE TABLE IF NOT EXISTS cats
(
    id          BIGINT generated by default as identity primary key,
    nick_name   TEXT   NOT NULL,
    breed       TEXT   NOT NULL,
    age         INT NOT NULL,
    description TEXT   NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS cats_idx ON cats(id);

-- changeset Юрий Калынбаев:3
CREATE TABLE IF NOT EXISTS dogs
(
    id          BIGINT generated by default as identity primary key,
    nick_name   TEXT   NOT NULL,
    breed       TEXT   NOT NULL,
    age         INT NOT NULL,
    description TEXT   NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS dogs_idx ON dogs(id);