-- liquibase formatted sql

-- -- changeset Юрий Калынбаев:5
CREATE TABLE users
(
    id                BIGINT generated by default as identity primary key,
    first_name        TEXT NOT NULL,
    last_name         TEXT NOT NULL,
    user_phone_number TEXT NOT NULL,
    user_email        TEXT NOT NULL,
    dog_id            BIGINT,
    cat_id            BIGINT,
    FOREIGN KEY (dog_id) REFERENCES dogs(id),
    FOREIGN KEY (cat_id) REFERENCES cats(id)
);


