package js6team3.tbot.entity.shelter;

import javax.persistence.*;

/**
 * The shelter general description
 *
 * @author Andrei Popov
 * Описание приюта
 */
@Entity
public class Shelter {
    /**
     * The shelter id (id bigint generated by default as identity primary key)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "id", nullable = false)
    private Long id;

    /**
     * The shelter name (varchar(255))
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * The shelter general information (text)
     */
    @Column(name = "information", nullable = false)
    private String information;

    /**
     * The shelter address (varchar(255))
      */
    @Column(name = "address", nullable = false)
    private String address;

    /**
     * The shelter contact's phone (varchar(255))
     */
    @Column(name = "phone", nullable = false)
    private String phone;

    /**
     * driving_link (varchar(255))
     */
    @Column(name = "driving_link", nullable = false)
    private String drivingLink;

    /**
     * working_hours (varchar(255))
     */
    @Column(name = "working_hours", nullable = false)
    private String workingHours;

    /**
     * territory_admission (text)
     */
    @Column(name = "territory_admission", nullable = false)
    private String territoryAdmission;

    /**
     * territory_staying (text)
     */
    @Column(name = "territory_staying", nullable = false)
    private String territoryStaying;

    /**
     * security_contacts (varchar(255))
     */
    @Column(name = "security_contacts", nullable = false)
    private String securityContacts;

    /**
     * animal_acquaintance (text)
     */
    @Column(name = "animal_acquaintance", nullable = false)
    private String animalAcquaintance;

    /**
     * document_list (text)
     */
    @Column(name = "document_list", nullable = false)
    private String documentList;

    /**
     * travel_recommendation (text)
     */
    @Column(name = "travel_recommendation", nullable = false)
    private String travelRecommendation;

    /**
     * child_arranging (text)
     */
    @Column(name = "child_arranging", nullable = false)
    private String childArranging;

    /**
     * adult_arranging (text)
     */
    @Column(name = "adult_arranging", nullable = false)
    private String adultArranging;

    /**
     * sick_arrangement (text)
     */
    @Column(name = "sick_arrangement", nullable = false)
    private String sickArrangement;

    /**
     * handler_advice (text)
     */
    @Column(name = "handler_advice", nullable = false)
    private String handlerAdvice;

    /**
     * refusal_reason (text)
     */
    @Column(name = "refusal_reason", nullable = false)
    private String refusalReason;
}