-- liquibase formatted sql

-- changeset Юрий Калынбаев:4
create table if not exists dog_photo
(
    id         bigint generated by default as identity primary key,
    file_path  varchar(255) not null,
    file_size  bigint       not null,
    media_type varchar(255) not null,
    photoDog   oid          not null,
    dog_id     bigint       not null,
    foreign key (dog_id) references dogs (id)
);
create unique index if not exists dog_photo_idx on dog_photo (id);