-- liquibase formatted sql

-- changeset Юрий Калынбаев:3
create table if not exists dogs
(
    id          bigint generated by default as identity primary key,
    nick_name   varchar(255) not null,
    breed       varchar(255) not null,
    age         bigint       not null,
    description varchar(255) not null
);
create unique index if not exists dogs_idx on dogs (id);