-- liquibase formatted sql

-- changeset Юрий Калынбаев:5
create table if not exists users
(
    id                 bigint generated by default as identity primary key,
    first_name         varchar(255) not null,
    last_name          varchar(255) not null,
    user_email         varchar(255) not null,
    users_phone_number varchar(255) not null,
    dog_id             bigint unique,
    foreign key (dog_id) references dogs (id),
    cat_id             bigint unique,
    foreign key (cat_id) references cats (id)
);
create unique index if not exists users_idx on users (last_name,first_name);


