-- liquibase formatted sql

-- changeset Юрий Калынбаев:2
create table if not exists cat_photo
(
    id         bigint generated by default as identity primary key,
    file_path  varchar(255) not null,
    file_size  bigint       not null,
    media_type varchar(255) not null,
    photoCat   oid          not null,
    cat_id     bigint       not null,
    foreign key (cat_id) references cats (id)
);
create unique index if not exists cat_photo_idx on cat_photo (id);